### PR TITLE
Add default rubocop configuration

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by iNecas** [comment]
Personally, I don't like `Style/StringLiterals`, a.k.a enforcing `''` when not using escape characters in `""`, but it might be just me :)

**Comment by ares** [comment]
Personally, I do :-) what as you wish, I've disabled `Style/StringLiterals`

**Comment by iNecas** [comment]
Works for me

**Comment by iNecas** [comment]
With rubocop 0.32.1, I'm getting this warnings:

```
.rubocop.yml: Style/BlockNesting has the wrong namespace - should be Metrics
.rubocop.yml: Style/LineLength has the wrong namespace - should be Metrics
.rubocop.yml: Style/MethodLength has the wrong namespace - should be Metrics
```

**Comment by ares** [comment]
Fixed, also disabled raise vs fail and 1.9 hash syntax cops.

**Comment by ares** [comment]
So what are the rules in this repo? Can I merge it? I'd like to provide an official link on wiki to download the config file.

**Comment by iNecas** [comment]
Next time, just merge it, merging now

**Comment by iNecas** [comment]
thx @ares !

**Pull request merged**
